<div class="mx-auto caseEliminar">
<h3 >Confirmar la eliminación de la categoría</h3>
<p class="parrafo">Está a punto de eliminar una categoria que contiene peliculas, ¿Está seguro?</p>
<a href="<?= BASE_URL ?>eliminarCategoriaDefinitivo/<?php echo $categoria->id; ?>" class="catStyle text-decoration-none text-reset mb-4">Si,eliminar</a>
<a href="<?= BASE_URL ?>categorias" class="catStyle text-decoration-none text-reset">Cancelar</a>
</div>