
<p class="parrafo">Agregar una categoria</p>

<form action="agregarCategoria" method="POST" class="my-4 mx-auto" >
        <div class="col-7">
            <div class="form-group" >
                <input class="form-control mx-auto " type="text" placeholder="Titulo" name="titulo" type="text" class=form-control>
            </div>
        </div>
        <div class="col-1 mb-2">

        </div>
    </div>

    <div class="form-group col-6">
        <textarea class="form-control " name="descripcion" rows="3" placeholder="Descripcion"></textarea>
    </div>
    <button type="submit" class="btn btn-success mt-2">Enviar</button>
    </div>
</form>
