<p class="parrafo">Agregar una pelicula</p>

<form action="agregarPelicula" method="POST" class="my-4 mx-auto">
    <div class="col-7">
        <div class="form-group ">
            <input class="form-control mx-auto " type="text" placeholder="Titulo" name="titulo" class=form-control>
            <input class="form-control mx-auto " type="date" placeholder="Titulo" name="fecha" class=form-control>

        </div>
    </div>
    <div class="col-7">
        <div class="form-group">
            <input class="form-control mx-auto " type="text" placeholder="Imagen de portada" name="imagen" class=form-control>
        </div>
    </div>
    <div class="form-group col-0">
        <select name="categoria_id" id="selectCat" class="mt-2">
            <?php
            foreach ($categorias as $categoria) {

            ?>
                <option id="option" value="<?php echo $categoria->id; ?>"><?php echo $categoria->nombre; ?></option>

            <?php } ?>
        </select>

    </div>
    <button type="submit" class="btn btn-success mt-4 mx-auto">Enviar</button>

</form>