
<?php if ($error) {?>
    <div class="alert alert-danger">
        <?= $error ?>
    </div>
<?php } ?>

<form method="POST" action="login" class="my-4 mx-auto" >
    <div class="form-group">
        <input type="text" class="form-control" name="usuario" required placeholder="Usuario">
    </div>
    <div class="form-group">
        <input type="password" class="form-control" name="password" required placeholder="Password">
    </div>
    <button type="submit" class="btn btn-primary">LOGIN</button>
</form>
<?php
?>